"""Tests for Markdown report rendering."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import probe_inference as pi


def test_markdown_report_links_to_llmprobe_commit_at_top():
    commit = "a47b8c02ae9e544966c4799699ad51d7e14bcf51"
    report = pi.render_markdown_report({"model": "test-model", "llmprobe_commit": commit})

    assert report.splitlines()[:3] == [
        "# Model capability probe: test-model",
        "",
        "Generated by [llmprobe](https://github.com/superleanai/llmprobe) "
        f"at commit [`{commit}`](https://github.com/superleanai/llmprobe/commit/{commit}).",
    ]


def test_capability_key_absent_says_no_data_please_rerun():
    """A JSON written before a capability existed has no key for it at all.

    The report must say there is no data rather than silently dropping the row or
    pretending the probe ran and skipped the test.
    """
    report = pi.render_markdown_report({"model": "test-model"})

    assert "| `QUOTE` | *(no data, please rerun the probing)* |" in report
    assert "## Quote-escaping test (`QUOTE`)\n\n*(no data, please rerun the probing)*" in report
    assert "- `QUOTE`: no data, please rerun the probing." in report
    assert "--no-quote-test" not in report


def test_capability_key_present_but_none_says_not_run_with_flag():
    """A key present but null means the probe ran and skipped the test on purpose."""
    report = pi.render_markdown_report({"model": "test-model", "quote_test": None})

    assert "| `QUOTE` | *(not run — rerun without `--no-quote-test`)* |" in report
    assert "| `QUOTE` | *(no data, please rerun the probing)* |" not in report
    assert "- `QUOTE` capability not tested (rerun without --no-quote-test)." in report
